import {supabase} from '@/integrations/supabase/client'
export type OrderStatus='pending'|'processing'|'waiting_callback'|'completed'|'rejected'
export type OrderRow={id:string;reference:string;account_type:'instant'|'challenge';account_size:number;price:number|string;broker:string;payment_method:string;coupon:string|null;status:string;decision_at:string;created_at:string}
export const effectiveStatus=(o:Pick<OrderRow,'status'|'decision_at'>):OrderStatus=>o.status==='pending'&&Date.parse(o.decision_at)<=Date.now()?'rejected':o.status as OrderStatus
export const reviewCountdown=(o:Pick<OrderRow,'status'|'decision_at'>)=>effectiveStatus(o)!=='pending'?null:`${Math.max(0,Math.ceil((Date.parse(o.decision_at)-Date.now())/60000))} min`
export const shortDate=(v:string)=>new Date(v).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})
export const shortTime=(v:string)=>new Date(v).toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})
export async function fetchOrders(){const{data,error}=await supabase.from('orders').select('*').order('created_at',{ascending:false});if(error)throw error;return(data??[]) as OrderRow[]}
export async function fetchOrder(reference:string){const{data,error}=await supabase.from('orders').select('*').eq('reference',reference).maybeSingle();if(error)throw error;return data as OrderRow|null}
export async function createOrder(input:{account_type:'instant'|'challenge';account_size:number;price:number;broker:string;payment_method:string;coupon?:string|null}){const{data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error('Sign in before placing an order.');const{data,error}=await supabase.from('orders').insert({...input,user_id:auth.user.id}).select('*').single();if(error)throw error;return data as OrderRow}
export type TicketRow={id:string;reference:string;subject:string;category:string;priority:string;status:string;created_at:string;updated_at:string}
export type MessageRow={id:string;author:string;body:string;created_at:string}
export async function fetchTickets(){const{data,error}=await supabase.from('support_tickets').select('*').order('updated_at',{ascending:false});if(error)throw error;return(data??[]) as TicketRow[]}
export async function fetchTicket(reference:string){const{data,error}=await supabase.from('support_tickets').select('*').eq('reference',reference).maybeSingle();if(error)throw error;if(!data)return null;const{data:messages,error:messageError}=await supabase.from('ticket_messages').select('id,author,body,created_at').eq('ticket_id',data.id).order('created_at');if(messageError)throw messageError;return{ticket:data as TicketRow,messages:(messages??[]) as MessageRow[]}}
export async function createTicket(input:{subject:string;category:string;priority:string;body:string}){const{data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error('Sign in to open a ticket.');const{data,error}=await supabase.from('support_tickets').insert({user_id:auth.user.id,subject:input.subject,category:input.category,priority:input.priority}).select('id,reference').single();if(error)throw error;const{error:messageError}=await supabase.from('ticket_messages').insert({ticket_id:data.id,user_id:auth.user.id,body:input.body});if(messageError)throw messageError;return data}
export async function replyToTicket(ticketId:string,body:string){const{data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error('Sign in to reply.');const{error}=await supabase.from('ticket_messages').insert({ticket_id:ticketId,user_id:auth.user.id,body});if(error)throw error;await supabase.from('support_tickets').update({updated_at:new Date().toISOString()}).eq('id',ticketId)}
export type ProfileRow={id:string;full_name:string|null;email:string|null;phone:string|null;country:string|null;created_at:string}
export async function fetchProfile(){const{data:auth}=await supabase.auth.getUser();if(!auth.user)return null;const{data,error}=await supabase.from('profiles').select('id,full_name,email,phone,country,created_at').eq('id',auth.user.id).maybeSingle();if(error)throw error;return data as ProfileRow|null}
export async function updateProfile(input:{full_name:string;phone:string;country:string}){const{data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error('Not signed in.');const{error}=await supabase.from('profiles').upsert({id:auth.user.id,email:auth.user.email??null,...input,updated_at:new Date().toISOString()});if(error)throw error}
