import pocketoption from '@/assets/broker-pocketoption.png.asset.json'
import quotex from '@/assets/broker-quotex.png.asset.json'
import binomo from '@/assets/broker-binomo.png.asset.json'
import olymptrade from '@/assets/broker-olymptrade.png.asset.json'
import tradowix from '@/assets/broker-tradowix.jpg.asset.json'
import btc from '@/assets/crypto-btc.png.asset.json'
import eth from '@/assets/crypto-eth.png.asset.json'
import usdt from '@/assets/crypto-usdt.png.asset.json'
export const assets={pocketoption:pocketoption.url,quotex:quotex.url,binomo:binomo.url,olymptrade:olymptrade.url,tradowix:tradowix.url,btc:btc.url,eth:eth.url,usdt:usdt.url}
export type Plan={size:number;price:number;dailyLoss:number;split:number;type:'instant'|'challenge';popular?:boolean;profitTarget?:number;drawdown?:number}
export const instantPlans:Plan[]=[{size:3000,price:70,dailyLoss:700,split:92,type:'instant'},{size:5000,price:116,dailyLoss:1167,split:92,type:'instant'},{size:8000,price:186,dailyLoss:1867,split:92,type:'instant'},{size:11000,price:256,dailyLoss:2567,split:92,type:'instant'},{size:15000,price:349,dailyLoss:3500,split:92,type:'instant'},{size:20000,price:466,dailyLoss:4667,split:92,type:'instant',popular:true},{size:25000,price:582,dailyLoss:5833,split:92,type:'instant'},{size:35000,price:815,dailyLoss:8167,split:92,type:'instant'},{size:50000,price:1165,dailyLoss:11667,split:92,type:'instant'}]
export const challengePlans:Plan[]=[{size:3000,price:48,profitTarget:1200,dailyLoss:900,drawdown:2000,split:92,type:'challenge'},{size:5000,price:81,profitTarget:2000,dailyLoss:1500,drawdown:3333,split:92,type:'challenge'},{size:8000,price:129,profitTarget:3200,dailyLoss:2400,drawdown:5333,split:92,type:'challenge',popular:true},{size:11000,price:178,profitTarget:4400,dailyLoss:3300,drawdown:7333,split:92,type:'challenge'},{size:25000,price:311,profitTarget:10000,dailyLoss:7500,drawdown:16667,split:92,type:'challenge'},{size:50000,price:484,profitTarget:20000,dailyLoss:15000,drawdown:33333,split:92,type:'challenge'}]
export const money=(n:number)=>`$${n.toLocaleString('en-US')}`
export const brokers=[{id:'pocketOption',name:'Pocket Option',logo:assets.pocketoption,note:'Fast execution, wide instrument range',desc:'Top-rated broker with flexible options trade modes and premium liquidity levels.'},{id:'quotex',name:'Quotex',logo:assets.quotex,note:'Low-latency order routing',desc:'Highly customizable UI and perfect modern trading interface for active clients.'},{id:'binomo',name:'Binomo',logo:assets.binomo,note:'Clean charting, mobile-first',desc:'Robust and steady execution speed, excellent for scalping models and rapid entries.'},{id:'olympTrade',name:'Olymp Trade',logo:assets.olymptrade,note:'Established platform, deep liquidity',desc:'Multi-market broker with deep indicators selection and lightning fast fills.'},{id:'tradowix',name:'Tradowix',logo:assets.tradowix,note:'Institutional grade speed, high reliability',desc:'Premium trading infrastructure with institutional grade speed.'}]
export const howItWorks=[['Choose your account','Pick an Instant account to start trading right away, or a Challenge account with a lower entry cost that unlocks funding once you hit the targets.'],['Complete the evaluation','Trade the simulated evaluation within the daily loss and drawdown limits. Hit the profit target and you move to the next stage.'],['Verification','We confirm your trading history against the account rules. Most verifications complete within one business day.'],['Get funded','Receive your funded account and start earning your profit split — up to 92% — on every payout cycle.']]
export const faqs=[['Accounts','When I select an account, how do I receive my account confirmation?','Once your payment is confirmed, your account credentials and platform access are sent to the email on file, typically within minutes. You can also track the status from your dashboard under Orders.'],['Challenge','What are the rules and profit targets for Challenge accounts?','Each Challenge account lists its profit target, daily loss limit, and maximum drawdown directly on the pricing card. You must reach the profit target without breaching either loss limit during the evaluation window.'],['Risk Rules','How does the Daily Loss Limit function on Instant and Challenge tracks?','The Daily Loss Limit resets every trading day at the platform’s server time. If your open and closed losses for the day reach that figure, trading is paused until the next reset.'],['Brokers','Which brokers and trading environments are supported?','Accounts currently run on Pocket Option, Quotex, Binomo, Olymp Trade, and Tradovate. You choose your broker when you select your account.'],['Payouts','How and when do I get paid?','Funded traders can request a payout on a recurring cycle once minimum profit is met. Payouts are sent via the payment method on file and are typically processed within 24-48 hours of request.'],['Accounts','Can I upgrade my account size later?','Yes. From your dashboard you can scale up to a larger account size once you’ve met the consistency and payout history requirements for your current tier.']]
export const reviews=[['Mohammed K.','AE','UAE','Dashboard is clean and payouts are reliable. Best prop firm experience I’ve had.'],['Sarah P.','GB','UK','Passed my evaluation in two weeks and got funded. The 92% split is real, no hidden fees.'],['Ahmed L.','PK','Pakistan','Payments are fast and secure. Highly recommend VEXO FUNDED for anyone serious about trading.'],['James R.','US','USA','Being able to track my drawdown and targets live made a real difference. Professional setup.']]
export const orders=[{id:'VEXO-10482',date:'2026-08-01',size:20000,type:'Challenge',broker:'Pocket Option',price:433,status:'completed'},{id:'VEXO-10471',date:'2026-07-24',size:8000,type:'Instant',broker:'Quotex',price:173,status:'processing'},{id:'VEXO-10459',date:'2026-07-15',size:11000,type:'Instant',broker:'Tradovate',price:238,status:'waiting_callback'},{id:'VEXO-10440',date:'2026-07-02',size:5000,type:'Challenge',broker:'Binomo',price:75,status:'rejected'},{id:'VEXO-10412',date:'2026-06-20',size:3000,type:'Instant',broker:'Olymp Trade',price:65,status:'pending'}]
export const tickets=[{id:'TCK-2291',subject:'Payout delayed for VEXO-10482',category:'Billing',priority:'High',status:'answered',updated:'2026-08-05',messages:[['user','My payout request from 3 days ago still shows pending. Can someone check?','Aug 2, 10:14 AM'],['support','Thanks for flagging this — we’re looking into the delay with our payment processor and will update you within 24 hours.','Aug 2, 2:47 PM'],['support','Your payout has been released. You should see it within the hour. Apologies for the wait.','Aug 5, 9:02 AM']]},{id:'TCK-2280',subject:'Question about drawdown reset time',category:'Challenge',priority:'Medium',status:'closed',updated:'2026-07-29',messages:[['user','Does the max drawdown reset daily or is it fixed for the whole evaluation?','Jul 28, 6:20 PM'],['support','Max drawdown is fixed for the full evaluation — only the daily loss limit resets each day.','Jul 29, 8:15 AM']]},{id:'TCK-2265',subject:'Cannot log in to Quotex broker account',category:'Technical',priority:'High',status:'open',updated:'2026-07-20',messages:[['user','Getting an invalid credentials error when I try to log into the broker platform.','Jul 20, 11:05 AM']]}]
export const crypto=[{id:'USDT ERC20',network:'Ethereum Network (ERC-20)',logo:assets.usdt,address:'0xD3MO2026FUND3D00000000000000000000ERC20'},{id:'USDT TRC20',network:'TRON Network (TRC-20)',logo:assets.usdt,address:'TDemoVEXOFundedPreviewWalletTRC20'},{id:'USDT BEP20',network:'BNB Smart Chain (BEP-20)',logo:assets.usdt,address:'0xD3MO2026FUND3D00000000000000000000BEP20'},{id:'Bitcoin',network:'Bitcoin Mainnet',logo:assets.btc,address:'bc1qdemoonlyvexofundedpreviewwallet'},{id:'Ethereum',network:'Ethereum Mainnet',logo:assets.eth,address:'0xD3MO2026FUND3D00000000000000000000ETH'}]
