import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {HeadContent,Outlet,Scripts,createRootRouteWithContext,useRouter} from '@tanstack/react-router'
import {useEffect,type ReactNode} from 'react'
import appCss from '../styles.css?url'
import {StatusPage} from '@/components/vexo/legal-status'
import {Button} from '@/components/vexo/ui'
import {reportLovableError} from '@/lib/lovable-error-reporting'
export const SITE_URL='https://project--d4b6037e-b2d8-4160-a495-87273e6609ed.lovable.app'
const organization={'@context':'https://schema.org','@type':'Organization',name:'VEXO FUNDED',url:SITE_URL,logo:`${SITE_URL}/favicon.svg`,description:'Proprietary trading evaluations and instant funding accounts from $3,000 to $50,000.'}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:'utf-8'},{name:'viewport',content:'width=device-width, initial-scale=1'},{title:'VEXO FUNDED — Funded Trading Accounts up to $50,000'},{name:'description',content:'Instant funding and challenge accounts with clear rules and up to 92% profit split.'},{name:'robots',content:'index, follow, max-image-preview:large'},{name:'theme-color',content:'#0b1112'},{property:'og:site_name',content:'VEXO FUNDED'},{property:'og:title',content:'VEXO FUNDED — Funded Trading Accounts up to $50,000'},{property:'og:description',content:'Instant funding and challenge accounts with clear rules and up to 92% profit split.'},{property:'og:type',content:'website'},{property:'og:image',content:`${SITE_URL}/og-cover.jpg`},{name:'twitter:card',content:'summary_large_image'},{name:'twitter:image',content:`${SITE_URL}/og-cover.jpg`}],links:[{rel:'stylesheet',href:appCss},{rel:'icon',href:'/favicon.svg',type:'image/svg+xml'},{rel:'canonical',href:SITE_URL},{rel:'preconnect',href:'https://fonts.googleapis.com'},{rel:'preconnect',href:'https://fonts.gstatic.com',crossOrigin:'anonymous'},{rel:'stylesheet',href:'https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@500;600&family=Manrope:wght@400;500;600;700&family=Sora:wght@500;600;700;800&display=swap'}],scripts:[{type:'application/ld+json',children:JSON.stringify(organization)}]}),shellComponent:Shell,component:Root,notFoundComponent:()=> <StatusPage kind="404"/>,errorComponent:ErrorBoundary})
function Shell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function Root(){const{queryClient}=Route.useRouteContext();const router=useRouter();useEffect(()=>{let active=true;let unsubscribe:(()=>void)|undefined;void import('@/integrations/supabase/client').then(({supabase})=>{if(!active)return;const{data}=supabase.auth.onAuthStateChange(event=>{if(!['SIGNED_IN','SIGNED_OUT','USER_UPDATED'].includes(event))return;router.invalidate();if(event!=='SIGNED_OUT')queryClient.invalidateQueries()});unsubscribe=()=>data.subscription.unsubscribe()});return()=>{active=false;unsubscribe?.()}},[queryClient,router]);return <QueryClientProvider client={queryClient}><Outlet/></QueryClientProvider>}
function ErrorBoundary({error,reset}:{error:unknown;reset?:()=>void}){const router=useRouter();useEffect(()=>reportLovableError(error,{boundary:'root'}),[error]);return <div className="grid min-h-screen place-items-center bg-background px-4 text-center"><div><h1 className="font-display text-3xl font-bold">This page didn't load</h1><p className="mt-3 text-muted">Try again or return to the home page.</p><div className="mt-6 flex justify-center gap-3"><Button onClick={()=>{router.invalidate();reset?.()}}>Try again</Button><Button to="/" variant="secondary">Go home</Button></div></div></div>}
