/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R500RouteImport } from './routes/500'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as BrokersRouteImport } from './routes/brokers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalRiskRouteImport } from './routes/legal.risk'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as AuthenticatedCheckoutDepositRouteImport } from './routes/_authenticated/checkout.deposit'
import { Route as AuthenticatedCheckoutDetailsRouteImport } from './routes/_authenticated/checkout.details'
import { Route as AuthenticatedCheckoutPaymentRouteImport } from './routes/_authenticated/checkout.payment'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardSecurityRouteImport } from './routes/_authenticated/dashboard.security'
import { Route as AuthenticatedDashboardOrdersIndexRouteImport } from './routes/_authenticated/dashboard.orders.index'
import { Route as AuthenticatedDashboardOrdersIdRouteImport } from './routes/_authenticated/dashboard.orders.$id'
import { Route as AuthenticatedDashboardSupportIndexRouteImport } from './routes/_authenticated/dashboard.support.index'
import { Route as AuthenticatedDashboardSupportIdRouteImport } from './routes/_authenticated/dashboard.support.$id'
import { Route as AuthenticatedDashboardSupportNewRouteImport } from './routes/_authenticated/dashboard.support.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersRoute = BrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRiskRoute = LegalRiskRouteImport.update({
  id: '/legal/risk',
  path: '/legal/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutDepositRoute =
  AuthenticatedCheckoutDepositRouteImport.update({
    id: '/checkout/deposit',
    path: '/checkout/deposit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckoutDetailsRoute =
  AuthenticatedCheckoutDetailsRouteImport.update({
    id: '/checkout/details',
    path: '/checkout/details',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckoutPaymentRoute =
  AuthenticatedCheckoutPaymentRouteImport.update({
    id: '/checkout/payment',
    path: '/checkout/payment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSecurityRoute =
  AuthenticatedDashboardSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersIndexRoute =
  AuthenticatedDashboardOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersIdRoute =
  AuthenticatedDashboardOrdersIdRouteImport.update({
    id: '/orders/$id',
    path: '/orders/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSupportIndexRoute =
  AuthenticatedDashboardSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSupportIdRoute =
  AuthenticatedDashboardSupportIdRouteImport.update({
    id: '/support/$id',
    path: '/support/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSupportNewRoute =
  AuthenticatedDashboardSupportNewRouteImport.update({
    id: '/support/new',
    path: '/support/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/accounts': typeof AccountsRoute
  '/brokers': typeof BrokersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/risk': typeof LegalRiskRoute
  '/legal/terms': typeof LegalTermsRoute
  '/checkout/deposit': typeof AuthenticatedCheckoutDepositRoute
  '/checkout/details': typeof AuthenticatedCheckoutDetailsRoute
  '/checkout/payment': typeof AuthenticatedCheckoutPaymentRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/security': typeof AuthenticatedDashboardSecurityRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/orders/$id': typeof AuthenticatedDashboardOrdersIdRoute
  '/dashboard/support/$id': typeof AuthenticatedDashboardSupportIdRoute
  '/dashboard/support/new': typeof AuthenticatedDashboardSupportNewRoute
  '/dashboard/orders/': typeof AuthenticatedDashboardOrdersIndexRoute
  '/dashboard/support/': typeof AuthenticatedDashboardSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/accounts': typeof AccountsRoute
  '/brokers': typeof BrokersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/risk': typeof LegalRiskRoute
  '/legal/terms': typeof LegalTermsRoute
  '/checkout/deposit': typeof AuthenticatedCheckoutDepositRoute
  '/checkout/details': typeof AuthenticatedCheckoutDetailsRoute
  '/checkout/payment': typeof AuthenticatedCheckoutPaymentRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/security': typeof AuthenticatedDashboardSecurityRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/orders/$id': typeof AuthenticatedDashboardOrdersIdRoute
  '/dashboard/support/$id': typeof AuthenticatedDashboardSupportIdRoute
  '/dashboard/support/new': typeof AuthenticatedDashboardSupportNewRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersIndexRoute
  '/dashboard/support': typeof AuthenticatedDashboardSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof R500Route
  '/accounts': typeof AccountsRoute
  '/brokers': typeof BrokersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/risk': typeof LegalRiskRoute
  '/legal/terms': typeof LegalTermsRoute
  '/_authenticated/checkout/deposit': typeof AuthenticatedCheckoutDepositRoute
  '/_authenticated/checkout/details': typeof AuthenticatedCheckoutDetailsRoute
  '/_authenticated/checkout/payment': typeof AuthenticatedCheckoutPaymentRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/security': typeof AuthenticatedDashboardSecurityRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/orders/$id': typeof AuthenticatedDashboardOrdersIdRoute
  '/_authenticated/dashboard/support/$id': typeof AuthenticatedDashboardSupportIdRoute
  '/_authenticated/dashboard/support/new': typeof AuthenticatedDashboardSupportNewRoute
  '/_authenticated/dashboard/orders/': typeof AuthenticatedDashboardOrdersIndexRoute
  '/_authenticated/dashboard/support/': typeof AuthenticatedDashboardSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/500'
    | '/accounts'
    | '/brokers'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/maintenance'
    | '/reset-password'
    | '/reviews'
    | '/signup'
    | '/support'
    | '/thank-you'
    | '/dashboard'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/risk'
    | '/legal/terms'
    | '/checkout/deposit'
    | '/checkout/details'
    | '/checkout/payment'
    | '/dashboard/profile'
    | '/dashboard/security'
    | '/dashboard/'
    | '/dashboard/orders/$id'
    | '/dashboard/support/$id'
    | '/dashboard/support/new'
    | '/dashboard/orders/'
    | '/dashboard/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/500'
    | '/accounts'
    | '/brokers'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/maintenance'
    | '/reset-password'
    | '/reviews'
    | '/signup'
    | '/support'
    | '/thank-you'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/risk'
    | '/legal/terms'
    | '/checkout/deposit'
    | '/checkout/details'
    | '/checkout/payment'
    | '/dashboard/profile'
    | '/dashboard/security'
    | '/dashboard'
    | '/dashboard/orders/$id'
    | '/dashboard/support/$id'
    | '/dashboard/support/new'
    | '/dashboard/orders'
    | '/dashboard/support'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/500'
    | '/accounts'
    | '/brokers'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/maintenance'
    | '/reset-password'
    | '/reviews'
    | '/signup'
    | '/support'
    | '/thank-you'
    | '/_authenticated/dashboard'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/risk'
    | '/legal/terms'
    | '/_authenticated/checkout/deposit'
    | '/_authenticated/checkout/details'
    | '/_authenticated/checkout/payment'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/security'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/orders/$id'
    | '/_authenticated/dashboard/support/$id'
    | '/_authenticated/dashboard/support/new'
    | '/_authenticated/dashboard/orders/'
    | '/_authenticated/dashboard/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R500Route: typeof R500Route
  AccountsRoute: typeof AccountsRoute
  BrokersRoute: typeof BrokersRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  ThankYouRoute: typeof ThankYouRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalRiskRoute: typeof LegalRiskRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers': {
      id: '/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof BrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/risk': {
      id: '/legal/risk'
      path: '/legal/risk'
      fullPath: '/legal/risk'
      preLoaderRoute: typeof LegalRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout/deposit': {
      id: '/_authenticated/checkout/deposit'
      path: '/checkout/deposit'
      fullPath: '/checkout/deposit'
      preLoaderRoute: typeof AuthenticatedCheckoutDepositRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/details': {
      id: '/_authenticated/checkout/details'
      path: '/checkout/details'
      fullPath: '/checkout/details'
      preLoaderRoute: typeof AuthenticatedCheckoutDetailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout/payment': {
      id: '/_authenticated/checkout/payment'
      path: '/checkout/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof AuthenticatedCheckoutPaymentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/security': {
      id: '/_authenticated/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof AuthenticatedDashboardSecurityRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders/': {
      id: '/_authenticated/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders/$id': {
      id: '/_authenticated/dashboard/orders/$id'
      path: '/orders/$id'
      fullPath: '/dashboard/orders/$id'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/support/': {
      id: '/_authenticated/dashboard/support/'
      path: '/support'
      fullPath: '/dashboard/support/'
      preLoaderRoute: typeof AuthenticatedDashboardSupportIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/support/$id': {
      id: '/_authenticated/dashboard/support/$id'
      path: '/support/$id'
      fullPath: '/dashboard/support/$id'
      preLoaderRoute: typeof AuthenticatedDashboardSupportIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/support/new': {
      id: '/_authenticated/dashboard/support/new'
      path: '/support/new'
      fullPath: '/dashboard/support/new'
      preLoaderRoute: typeof AuthenticatedDashboardSupportNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardSecurityRoute: typeof AuthenticatedDashboardSecurityRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardOrdersIdRoute: typeof AuthenticatedDashboardOrdersIdRoute
  AuthenticatedDashboardSupportIdRoute: typeof AuthenticatedDashboardSupportIdRoute
  AuthenticatedDashboardSupportNewRoute: typeof AuthenticatedDashboardSupportNewRoute
  AuthenticatedDashboardOrdersIndexRoute: typeof AuthenticatedDashboardOrdersIndexRoute
  AuthenticatedDashboardSupportIndexRoute: typeof AuthenticatedDashboardSupportIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardSecurityRoute: AuthenticatedDashboardSecurityRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardOrdersIdRoute: AuthenticatedDashboardOrdersIdRoute,
    AuthenticatedDashboardSupportIdRoute: AuthenticatedDashboardSupportIdRoute,
    AuthenticatedDashboardSupportNewRoute:
      AuthenticatedDashboardSupportNewRoute,
    AuthenticatedDashboardOrdersIndexRoute:
      AuthenticatedDashboardOrdersIndexRoute,
    AuthenticatedDashboardSupportIndexRoute:
      AuthenticatedDashboardSupportIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedCheckoutDepositRoute: typeof AuthenticatedCheckoutDepositRoute
  AuthenticatedCheckoutDetailsRoute: typeof AuthenticatedCheckoutDetailsRoute
  AuthenticatedCheckoutPaymentRoute: typeof AuthenticatedCheckoutPaymentRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedCheckoutDepositRoute: AuthenticatedCheckoutDepositRoute,
  AuthenticatedCheckoutDetailsRoute: AuthenticatedCheckoutDetailsRoute,
  AuthenticatedCheckoutPaymentRoute: AuthenticatedCheckoutPaymentRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R500Route: R500Route,
  AccountsRoute: AccountsRoute,
  BrokersRoute: BrokersRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  ThankYouRoute: ThankYouRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalRiskRoute: LegalRiskRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
