/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R500RouteImport } from './routes/500'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as BrokersRouteImport } from './routes/brokers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as CheckoutDepositRouteImport } from './routes/checkout.deposit'
import { Route as CheckoutDetailsRouteImport } from './routes/checkout.details'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout.payment'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalRiskRouteImport } from './routes/legal.risk'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard.orders.index'
import { Route as DashboardOrdersIdRouteImport } from './routes/dashboard.orders.$id'
import { Route as DashboardSupportIndexRouteImport } from './routes/dashboard.support.index'
import { Route as DashboardSupportIdRouteImport } from './routes/dashboard.support.$id'
import { Route as DashboardSupportNewRouteImport } from './routes/dashboard.support.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersRoute = BrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutDepositRoute = CheckoutDepositRouteImport.update({
  id: '/checkout/deposit',
  path: '/checkout/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutDetailsRoute = CheckoutDetailsRouteImport.update({
  id: '/checkout/details',
  path: '/checkout/details',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/checkout/payment',
  path: '/checkout/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRiskRoute = LegalRiskRouteImport.update({
  id: '/legal/risk',
  path: '/legal/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersIdRoute = DashboardOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportIndexRoute = DashboardSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportIdRoute = DashboardSupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportNewRoute = DashboardSupportNewRouteImport.update({
  id: '/support/new',
  path: '/support/new',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/accounts': typeof AccountsRoute
  '/brokers': typeof BrokersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/verify-email': typeof VerifyEmailRoute
  '/checkout/deposit': typeof CheckoutDepositRoute
  '/checkout/details': typeof CheckoutDetailsRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/risk': typeof LegalRiskRoute
  '/legal/terms': typeof LegalTermsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/dashboard/support/$id': typeof DashboardSupportIdRoute
  '/dashboard/support/new': typeof DashboardSupportNewRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/support/': typeof DashboardSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/accounts': typeof AccountsRoute
  '/brokers': typeof BrokersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/verify-email': typeof VerifyEmailRoute
  '/checkout/deposit': typeof CheckoutDepositRoute
  '/checkout/details': typeof CheckoutDetailsRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/risk': typeof LegalRiskRoute
  '/legal/terms': typeof LegalTermsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/dashboard/support/$id': typeof DashboardSupportIdRoute
  '/dashboard/support/new': typeof DashboardSupportNewRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
  '/dashboard/support': typeof DashboardSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/500': typeof R500Route
  '/accounts': typeof AccountsRoute
  '/brokers': typeof BrokersRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/reviews': typeof ReviewsRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/verify-email': typeof VerifyEmailRoute
  '/checkout/deposit': typeof CheckoutDepositRoute
  '/checkout/details': typeof CheckoutDetailsRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/risk': typeof LegalRiskRoute
  '/legal/terms': typeof LegalTermsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/dashboard/support/$id': typeof DashboardSupportIdRoute
  '/dashboard/support/new': typeof DashboardSupportNewRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
  '/dashboard/support/': typeof DashboardSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/500'
    | '/accounts'
    | '/brokers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/maintenance'
    | '/reviews'
    | '/signup'
    | '/support'
    | '/thank-you'
    | '/verify-email'
    | '/checkout/deposit'
    | '/checkout/details'
    | '/checkout/payment'
    | '/dashboard/profile'
    | '/dashboard/security'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/risk'
    | '/legal/terms'
    | '/dashboard/'
    | '/dashboard/orders/$id'
    | '/dashboard/support/$id'
    | '/dashboard/support/new'
    | '/dashboard/orders/'
    | '/dashboard/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/500'
    | '/accounts'
    | '/brokers'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/maintenance'
    | '/reviews'
    | '/signup'
    | '/support'
    | '/thank-you'
    | '/verify-email'
    | '/checkout/deposit'
    | '/checkout/details'
    | '/checkout/payment'
    | '/dashboard/profile'
    | '/dashboard/security'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/risk'
    | '/legal/terms'
    | '/dashboard'
    | '/dashboard/orders/$id'
    | '/dashboard/support/$id'
    | '/dashboard/support/new'
    | '/dashboard/orders'
    | '/dashboard/support'
  id:
    | '__root__'
    | '/'
    | '/500'
    | '/accounts'
    | '/brokers'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/maintenance'
    | '/reviews'
    | '/signup'
    | '/support'
    | '/thank-you'
    | '/verify-email'
    | '/checkout/deposit'
    | '/checkout/details'
    | '/checkout/payment'
    | '/dashboard/profile'
    | '/dashboard/security'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/risk'
    | '/legal/terms'
    | '/dashboard/'
    | '/dashboard/orders/$id'
    | '/dashboard/support/$id'
    | '/dashboard/support/new'
    | '/dashboard/orders/'
    | '/dashboard/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R500Route: typeof R500Route
  AccountsRoute: typeof AccountsRoute
  BrokersRoute: typeof BrokersRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ReviewsRoute: typeof ReviewsRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  ThankYouRoute: typeof ThankYouRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CheckoutDepositRoute: typeof CheckoutDepositRoute
  CheckoutDetailsRoute: typeof CheckoutDetailsRoute
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalRiskRoute: typeof LegalRiskRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers': {
      id: '/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof BrokersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/deposit': {
      id: '/checkout/deposit'
      path: '/checkout/deposit'
      fullPath: '/checkout/deposit'
      preLoaderRoute: typeof CheckoutDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/details': {
      id: '/checkout/details'
      path: '/checkout/details'
      fullPath: '/checkout/details'
      preLoaderRoute: typeof CheckoutDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/checkout/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/risk': {
      id: '/legal/risk'
      path: '/legal/risk'
      fullPath: '/legal/risk'
      preLoaderRoute: typeof LegalRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders/$id': {
      id: '/dashboard/orders/$id'
      path: '/orders/$id'
      fullPath: '/dashboard/orders/$id'
      preLoaderRoute: typeof DashboardOrdersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support/': {
      id: '/dashboard/support/'
      path: '/support'
      fullPath: '/dashboard/support/'
      preLoaderRoute: typeof DashboardSupportIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support/$id': {
      id: '/dashboard/support/$id'
      path: '/support/$id'
      fullPath: '/dashboard/support/$id'
      preLoaderRoute: typeof DashboardSupportIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support/new': {
      id: '/dashboard/support/new'
      path: '/support/new'
      fullPath: '/dashboard/support/new'
      preLoaderRoute: typeof DashboardSupportNewRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOrdersIdRoute: typeof DashboardOrdersIdRoute
  DashboardSupportIdRoute: typeof DashboardSupportIdRoute
  DashboardSupportNewRoute: typeof DashboardSupportNewRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
  DashboardSupportIndexRoute: typeof DashboardSupportIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOrdersIdRoute: DashboardOrdersIdRoute,
  DashboardSupportIdRoute: DashboardSupportIdRoute,
  DashboardSupportNewRoute: DashboardSupportNewRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
  DashboardSupportIndexRoute: DashboardSupportIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R500Route: R500Route,
  AccountsRoute: AccountsRoute,
  BrokersRoute: BrokersRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  ReviewsRoute: ReviewsRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  ThankYouRoute: ThankYouRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CheckoutDepositRoute: CheckoutDepositRoute,
  CheckoutDetailsRoute: CheckoutDetailsRoute,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalRiskRoute: LegalRiskRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
