import {useEffect,useState,type FormEvent} from 'react'
import {Link,useNavigate,useSearch} from '@tanstack/react-router'
import {CheckCircle2,Loader2,Mail} from 'lucide-react'
import {supabase} from '@/integrations/supabase/client'
import {lovable} from '@/integrations/lovable'
import {AuthShell} from './layouts'
import {Button,Field} from './ui'
const safe=(v:unknown)=>typeof v==='string'&&v.startsWith('/')&&!v.startsWith('//')?v:'/dashboard'
function Alert({children}:{children:string}){return <p className="rounded-md border border-error/30 bg-error/10 p-3 text-sm text-error">{children}</p>}
function Or(){return <div className="my-6 flex items-center gap-3 text-xs text-dim"><i className="h-px flex-1 bg-line"/>or continue with<i className="h-px flex-1 bg-line"/></div>}
function Google({error,redirect='/dashboard'}:{error:(v:string)=>void;redirect?:string}){const[busy,setBusy]=useState(false);return <Button type="button" variant="secondary" className="w-full" disabled={busy} onClick={async()=>{setBusy(true);error('');sessionStorage.setItem('vexo_oauth_redirect',safe(redirect));const result=await lovable.auth.signInWithOAuth('google',{redirect_uri:`${window.location.origin}/auth/callback`,extraParams:{prompt:'select_account'}});if(result.error){error(result.error.message||'Google sign-in could not be completed.');setBusy(false)}else if(!result.redirected)window.location.assign(safe(redirect))}}>{busy&&<Loader2 className="animate-spin" size={16}/>}Continue with Google</Button>}
export function Login(){const nav=useNavigate();const search=useSearch({strict:false}) as{redirect?:string};const[form,setForm]=useState({email:'',password:''});const[error,setError]=useState('');const[busy,setBusy]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');const{error:x}=await supabase.auth.signInWithPassword(form);setBusy(false);if(x)setError(x.message==='Invalid login credentials'?'Email or password is incorrect.':x.message);else nav({to:safe(search.redirect)})};return <AuthShell title="Welcome back" subtitle="Sign in to manage accounts, orders and support."><form onSubmit={submit} className="space-y-5">{error&&<Alert>{error}</Alert>}<Field label="Email" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Field label="Password" type="password" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><div className="text-right text-sm"><Link to="/forgot-password" className="text-brand">Forgot password?</Link></div><Button className="w-full" disabled={busy}>{busy&&<Loader2 className="animate-spin" size={16}/>}Sign in</Button></form><Or/><Google error={setError} redirect={safe(search.redirect)}/><p className="mt-6 text-center text-sm text-muted">New to VEXO? <Link to="/signup" className="text-brand">Create account</Link></p></AuthShell>}
export function Signup(){const nav=useNavigate();const[form,setForm]=useState({name:'',email:'',password:'',confirm:'',country:'United States'});const[error,setError]=useState('');const[busy,setBusy]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();if(form.password.length<8){setError('Password must be at least 8 characters.');return}if(form.password!==form.confirm){setError('Passwords do not match.');return}setBusy(true);const{error:x}=await supabase.auth.signUp({email:form.email,password:form.password,options:{data:{full_name:form.name,country:form.country}}});if(x){setError(x.message);setBusy(false);return}const{error:y}=await supabase.auth.signInWithPassword({email:form.email,password:form.password});setBusy(false);if(y)setError(y.message);else nav({to:'/dashboard'})};return <AuthShell title="Create your account" subtitle="Open your VEXO workspace in minutes."><form onSubmit={submit} className="space-y-4">{error&&<Alert>{error}</Alert>}<Field label="Full name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Field label="Email" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Field label="Password" type="password" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><Field label="Confirm password" type="password" required value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/><label className="block text-sm text-copy">Country<select value={form.country} onChange={e=>setForm({...form,country:e.target.value})} className="mt-1.5 w-full rounded-md border border-line bg-ink p-3"><option>United States</option><option>United Kingdom</option><option>United Arab Emirates</option><option>Pakistan</option><option>India</option><option>Other</option></select></label><label className="flex gap-2 text-xs text-muted"><input type="checkbox" required/>I agree to the Terms and Risk Disclosure.</label><Button className="w-full" disabled={busy}>Create account</Button></form><Or/><Google error={setError}/></AuthShell>}
export function Forgot(){const[email,setEmail]=useState('');const[done,setDone]=useState(false);const[error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();const{error:x}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});if(x)setError(x.message);else setDone(true)};return <AuthShell title="Reset your password" subtitle="Receive a secure password reset link.">{done?<div className="rounded-lg border border-success/30 bg-success/10 p-6 text-center"><CheckCircle2 className="mx-auto text-success"/><b className="mt-3 block">Check your inbox</b><p className="mt-2 text-sm text-muted">If the account exists, a reset link is on its way.</p></div>:<form onSubmit={submit} className="space-y-5">{error&&<Alert>{error}</Alert>}<Field label="Email" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/><Button className="w-full"><Mail size={16}/>Send reset link</Button></form>}</AuthShell>}
export function ResetPassword(){const nav=useNavigate();const[p,setP]=useState('');const[c,setC]=useState('');const[error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();if(p.length<8||p!==c){setError('Use matching passwords of at least 8 characters.');return}const{error:x}=await supabase.auth.updateUser({password:p});if(x)setError(x.message);else nav({to:'/dashboard'})};return <AuthShell title="Set a new password" subtitle="Choose a new secure password."><form onSubmit={submit} className="space-y-5">{error&&<Alert>{error}</Alert>}<Field label="New password" type="password" value={p} onChange={e=>setP(e.target.value)} required/><Field label="Confirm password" type="password" value={c} onChange={e=>setC(e.target.value)} required/><Button className="w-full">Update password</Button></form></AuthShell>}

export function AuthCallback(){const nav=useNavigate();const[error,setError]=useState('');useEffect(()=>{let active=true;const finish=async()=>{const{data,error:x}=await supabase.auth.getSession();if(!active)return;if(x||!data.session){setError('Google sign-in could not be completed. Please try again.');return}const target=safe(sessionStorage.getItem('vexo_oauth_redirect'));sessionStorage.removeItem('vexo_oauth_redirect');nav({to:target})};void finish();return()=>{active=false}},[nav]);return <AuthShell title="Completing sign in" subtitle="Your secure Google session is being prepared.">{error?<><Alert>{error}</Alert><Button to="/login" className="mt-5 w-full">Return to sign in</Button></>:<div className="flex items-center gap-3 text-copy"><Loader2 className="animate-spin text-brand"/>Signing you in…</div>}</AuthShell>}
