import { Link, Outlet } from '@tanstack/react-router'
import { useEffect, useState, type ReactNode } from 'react'
import { Bell, Cookie, LayoutDashboard, LifeBuoy, ListOrdered, LogOut, Menu, ShieldCheck, User, X } from 'lucide-react'
import { Badge, Button, Logo, cn } from './ui'
import { LiveSupport } from './live-support'

const links = [['/accounts','Accounts'],['/brokers','Brokers'],['/how-it-works','How It Works'],['/faq','FAQ'],['/reviews','Reviews'],['/support','Support']] as const

export function SiteLayout({ children }: { children: ReactNode }) {
  return <div className="min-h-screen overflow-x-hidden"><Navbar/>{children}<Footer/><CookieBanner/><LiveSupport/></div>
}

function Navbar() {
  const [open,setOpen] = useState(false)
  const [scrolled,setScrolled] = useState(false)
  useEffect(() => { const update=()=>setScrolled(scrollY>12); addEventListener('scroll',update); return()=>removeEventListener('scroll',update) },[])
  return <header className={cn('fixed top-0 z-50 w-full border-b border-transparent py-4 transition',scrolled&&'glass border-line py-2.5')}>
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 sm:px-6"><Logo/><div className="hidden items-center gap-1 lg:flex">{links.map(([to,label])=><Link key={to} to={to} className="rounded-sm px-3 py-2 text-xs font-medium uppercase text-muted transition hover:bg-soft hover:text-bright" activeProps={{className:'bg-brand/10 text-brand-soft'}}>{label}</Link>)}</div><div className="hidden items-center gap-2 lg:flex"><Button to="/login" variant="ghost" size="sm">Sign In</Button><Button to="/accounts" size="sm">Open Account</Button></div><button aria-label="Menu" onClick={()=>setOpen(!open)} className="rounded-sm border border-line bg-panel p-2.5 lg:hidden">{open?<X size={20}/>:<Menu size={20}/>}</button></nav>
    {open&&<div className="glass mt-3 border-y border-line px-5 py-4 lg:hidden">{links.map(([to,label])=><Link key={to} to={to} onClick={()=>setOpen(false)} className="block rounded-sm border-b border-line px-3 py-3 text-sm text-copy last:border-0 hover:bg-soft">{label}</Link>)}<div className="mt-4 grid grid-cols-2 gap-2"><Button to="/login" variant="secondary">Sign In</Button><Button to="/accounts">Open Account</Button></div></div>}
  </header>
}

function Footer() {
  const groups=[['Product',[['/accounts','Accounts'],['/brokers','Brokers'],['/how-it-works','How It Works'],['/reviews','Reviews']]],['Support',[['/faq','FAQ'],['/support','Support Center'],['/contact','Contact Us']]],['Legal',[['/legal/terms','Terms & Agreement'],['/legal/privacy','Privacy Agreement'],['/legal/refund','Refund Policy'],['/legal/risk','Risk Disclosure'],['/legal/cookies','Cookies']]]] as const
  return <footer className="bg-ink"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-6"><div className="grid grid-cols-2 gap-10 border-b border-line pb-12 md:grid-cols-5"><div className="col-span-2"><Logo/><p className="mt-5 max-w-sm text-sm leading-relaxed text-muted">Simulated evaluations for aspiring traders. Prove your edge, get funded, and keep up to 92% of the profits you generate on your funded account.</p><div className="mt-6 inline-flex items-center gap-2 border-l-2 border-success pl-3 text-xs text-copy"><i className="h-1.5 w-1.5 rounded-full bg-success"/> Operations online 24/7</div></div>{groups.map(([title,items])=><div key={title}><h4 className="font-display text-xs font-semibold uppercase text-copy kicker">{title}</h4><ul className="mt-5 space-y-3">{items.map(([to,label])=><li key={to}><Link to={to} className="text-sm text-muted transition hover:text-brand">{label}</Link></li>)}</ul></div>)}</div><div className="pt-7 text-xs leading-relaxed text-dim"><strong className="text-muted">Risk Disclosure:</strong> Evaluation and Instant accounts are simulated trading environments funded by account fees; no client funds are traded on live markets during the evaluation phase. Profit splits on funded accounts are paid from firm capital according to your account agreement. Trading involves risk and past performance is not indicative of future results. VEXO FUNDED does not provide investment advice.<div className="mt-5 flex flex-wrap justify-between gap-3 border-t border-line pt-5"><span>© 2026 VEXO FUNDED. All rights reserved.</span><span className="font-mono uppercase kicker">Built for traders, by traders.</span></div></div></div></footer>
}

function CookieBanner() {
  const [show,setShow]=useState(true)
  if(!show) return null
  return <div className="fixed bottom-3 left-3 right-3 z-50 mx-auto max-w-2xl rounded-md border border-line-strong bg-panel p-4 shadow-panel"><div className="flex items-start gap-3"><Cookie className="mt-1 shrink-0 text-brand" size={18}/><div className="flex-1"><p className="text-sm font-semibold">Cookie preferences</p><p className="mt-1 text-xs text-muted">Essential cookies keep the platform working. Optional cookies improve your experience.</p></div><button aria-label="Dismiss" onClick={()=>setShow(false)} className="text-muted hover:text-bright"><X size={18}/></button></div><div className="mt-3 flex justify-end gap-2"><Button size="sm" variant="ghost" onClick={()=>setShow(false)}>Essential only</Button><Button size="sm" onClick={()=>setShow(false)}>Accept all</Button></div></div>
}

const dash = [['/dashboard','Dashboard',LayoutDashboard],['/dashboard/orders','Orders',ListOrdered],['/dashboard/support','Support Tickets',LifeBuoy],['/dashboard/profile','Profile',User],['/dashboard/security','Security',ShieldCheck]] as const

export function DashboardLayout() {
  const [open,setOpen]=useState(false)
  const [notifs,setNotifs]=useState(false)
  return <div className="flex min-h-screen bg-background"><aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-line bg-ink lg:block"><DashNav/></aside>{open&&<div className="fixed inset-0 z-40 bg-overlay lg:hidden" onClick={()=>setOpen(false)}><aside className="h-full w-72 bg-ink" onClick={event=>event.stopPropagation()}><DashNav close={()=>setOpen(false)}/></aside></div>}<div className="min-w-0 flex-1 lg:pl-64"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-line bg-background/95 px-5 backdrop-blur md:px-7"><button aria-label="Open dashboard menu" className="rounded-sm border border-line p-2 lg:hidden" onClick={()=>setOpen(true)}><Menu/></button><div className="hidden items-center gap-2 text-[10px] uppercase text-dim kicker lg:flex"><i className="h-1.5 w-1.5 rounded-full bg-success"/> Systems operational</div><div className="relative flex items-center gap-3"><button aria-label="Notifications" onClick={()=>setNotifs(!notifs)} className="relative rounded-sm border border-line bg-panel p-2.5"><Bell size={16}/><i className="absolute right-1 top-1 h-1.5 w-1.5 rounded-full bg-action"/></button>{notifs&&<CardPopover/>}<Link to="/dashboard/profile" className="flex items-center gap-2 border-l border-line pl-3"><span className="grid h-8 w-8 place-items-center rounded-sm bg-brand/15 text-xs font-bold text-brand">AT</span><span className="hidden text-xs sm:block">Alex Trader</span></Link></div></header><main className="p-5 md:p-8"><Outlet/></main></div></div>
}

function CardPopover(){return <div className="absolute right-11 top-12 w-80 rounded-md border border-line-strong bg-panel p-4 shadow-panel"><div className="flex justify-between border-b border-line pb-3"><b className="text-sm">Notifications</b><span className="text-xs text-dim">2 total</span></div><div className="mt-3 space-y-2 text-xs"><p className="rounded-sm bg-soft p-3"><b>Order completed</b><br/><span className="text-muted">Your VEXO-10482 account is ready.</span></p><p className="rounded-sm bg-soft p-3"><b>Support replied</b><br/><span className="text-muted">Your payout ticket has an update.</span></p></div></div>}

function DashNav({close}:{close?:()=>void}){return <div className="flex h-full flex-col"><div className="border-b border-line px-5 py-5"><Logo/></div><div className="px-5 py-4 text-[9px] uppercase text-dim kicker">Client workspace</div><nav className="flex-1 space-y-1 px-3">{dash.map(([to,label,Icon])=><Link key={to} to={to} onClick={close} activeProps={{className:'border-brand/25 bg-brand/10 text-brand-soft'}} className="flex items-center gap-3 rounded-sm border border-transparent px-3 py-2.5 text-xs font-medium uppercase text-muted transition hover:bg-soft hover:text-bright"><Icon size={16}/>{label}</Link>)}</nav><Link to="/login" className="m-3 flex items-center gap-3 border-t border-line px-3 py-4 text-xs uppercase text-muted"><LogOut size={16}/>Logout</Link></div>}

export function AuthShell({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <div className="flex min-h-screen"><div className="flex w-full flex-col justify-center px-6 py-12 lg:w-[46%] lg:px-16 xl:px-24"><div className="mb-12"><Logo/></div><div className="mx-auto w-full max-w-sm"><p className="mb-3 text-[10px] uppercase text-brand kicker">Secure client access</p><h1 className="font-display text-3xl font-semibold">{title}</h1><p className="mt-2 text-sm text-muted">{subtitle}</p><div className="mt-8">{children}</div></div></div><div className="relative hidden flex-1 overflow-hidden border-l border-line bg-ink lg:block"><div className="absolute inset-0 grid-bg market-bg"/><Equity/><div className="absolute left-14 top-14 max-w-md"><span className="inline-flex items-center gap-2 text-[10px] font-medium uppercase text-success kicker"><i className="h-1.5 w-1.5 rounded-full bg-success"/> VEXO operations online</span><p className="mt-5 font-display text-4xl font-semibold leading-tight">A disciplined path from evaluation to funded capital.</p></div><div className="absolute bottom-14 left-14 right-14 border-l-2 border-brand pl-5"><blockquote className="font-display text-xl">“The clearest rules and the fastest payouts of any firm I've traded with.”</blockquote><p className="mt-3 text-xs uppercase text-muted kicker">Sarah P. · Funded Trader · UK</p></div></div></div>}

export function Equity(){return <svg className="pointer-events-none absolute inset-x-0 bottom-0 h-2/3 w-full opacity-55" viewBox="0 0 1000 400" preserveAspectRatio="none"><path d="M0 340 C100 320 160 360 250 280 S390 250 450 230 S570 290 630 190 S760 210 820 120 S930 130 1000 45" fill="none" stroke="var(--brand)" strokeWidth="2" className="draw"/><path d="M0 340 C100 320 160 360 250 280 S390 250 450 230 S570 290 630 190 S760 210 820 120 S930 130 1000 45 V400 H0Z" fill="url(#vexo-equity)"/><defs><linearGradient id="vexo-equity" x1="0" y1="0" x2="0" y2="1"><stop stopColor="var(--brand)" stopOpacity=".16"/><stop offset="1" stopColor="var(--brand)" stopOpacity="0"/></linearGradient></defs></svg>}