import {useState,type ButtonHTMLAttributes,type InputHTMLAttributes,type ReactNode} from 'react'
import {Link} from '@tanstack/react-router'
import {Check,Eye,EyeOff} from 'lucide-react'
import {twMerge} from 'tailwind-merge'
export const cn=(...v:(string|false|null|undefined)[])=>twMerge(v.filter(Boolean).join(' '))
export function Mark({className}:{className?:string}){return <svg viewBox="0 0 40 40" className={cn('h-9 w-9',className)} aria-hidden><path fill="currentColor" d="M4 6h9l7 19L27 6h9L22 35h-5L4 6Z"/><path fill="var(--action)" d="M12 6h7l4 11-4 8L12 6Z"/></svg>}
export function Logo({compact=false}:{compact?:boolean}){return <span className="inline-flex items-center gap-2 text-brand"><Mark/>{!compact&&<span className="font-display text-lg font-extrabold text-foreground">VEXO <em className="not-italic text-action">FUNDED</em></span>}</span>}
type Btn=ButtonHTMLAttributes<HTMLButtonElement>&{children:ReactNode;to?:string;variant?:'primary'|'secondary'|'ghost'|'outline';size?:'sm'|'md'|'lg'}
export function Button({children,to,variant='primary',size='md',className,...rest}:Btn){const styles=cn('inline-flex min-h-10 items-center justify-center gap-2 rounded-md border font-semibold transition focus-visible:outline-none disabled:opacity-45',size==='sm'?'px-3 py-2 text-xs':size==='lg'?'px-6 py-3.5 text-base':'px-4 py-2.5 text-sm',variant==='primary'?'border-action bg-action text-action-foreground hover:bg-action/90':variant==='secondary'?'border-line-strong bg-panel text-foreground hover:bg-panel-raised':variant==='outline'?'border-brand/50 bg-transparent text-brand hover:bg-brand/10':'border-transparent bg-transparent text-copy hover:bg-soft',className);return to?<Link to={to} className={styles}>{children}</Link>:<button className={styles} {...rest}>{children}</button>}
export function Card({children,className}:{children:ReactNode;className?:string}){return <div className={cn('rounded-lg border border-line bg-card shadow-card',className)}>{children}</div>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'neutral'|'brand'|'success'|'warning'|'error'}){return <span className={cn('inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-[11px] font-bold uppercase',tone==='brand'?'border-brand/30 bg-brand/10 text-brand-soft':tone==='success'?'border-success/30 bg-success/10 text-success':tone==='warning'?'border-warning/30 bg-warning/10 text-warning':tone==='error'?'border-error/30 bg-error/10 text-error':'border-line bg-soft text-muted')}>{children}</span>}
export function Section({children,className}:{children:ReactNode;className?:string}){return <section className={cn('px-4 py-20 sm:px-6 lg:px-8',className)}><div className="mx-auto max-w-7xl">{children}</div></section>}
export function Field({label,className,...props}:InputHTMLAttributes<HTMLInputElement>&{label:string}){const[show,setShow]=useState(false);const pass=props.type==='password';return <label className="block text-sm font-medium text-copy">{label}<span className="relative mt-1.5 block"><input {...props} type={pass&&show?'text':props.type} className={cn('w-full rounded-md border border-line bg-ink px-3.5 py-3 text-foreground placeholder:text-dim focus:border-brand',pass&&'pr-11',className)}/>{pass&&<button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button>}</span></label>}
export function Status({value}:{value:string}){const tone=value==='completed'?'success':value==='rejected'?'error':value==='pending'||value==='open'?'warning':'brand';return <Badge tone={tone}>{value.replace('_',' ')}</Badge>}
export function PlanCard({plan}:{plan:import('@/lib/vexo-data').Plan}){const key=`${plan.type}-${plan.size}`;return <Card className={cn('relative flex h-full flex-col p-5',plan.popular&&'border-action/50')}>{plan.popular&&<Badge tone="warning">Most popular</Badge>}<p className="mt-4 text-xs font-bold uppercase text-muted">{plan.type==='instant'?'Instant funding':'Two-step challenge'}</p><h3 className="num mt-2 text-3xl font-bold">${plan.size.toLocaleString()}</h3><div className="my-5 h-px bg-line"/><ul className="space-y-3 text-sm text-copy"><li className="flex justify-between"><span>Daily loss</span><b className="num">${plan.dailyLoss.toLocaleString()}</b></li>{plan.profitTarget&&<li className="flex justify-between"><span>Profit target</span><b className="num">${plan.profitTarget.toLocaleString()}</b></li>}{plan.drawdown&&<li className="flex justify-between"><span>Max drawdown</span><b className="num">${plan.drawdown.toLocaleString()}</b></li>}<li className="flex justify-between"><span>Profit split</span><b className="num">{plan.split}%</b></li></ul><div className="mt-auto pt-6"><Button to={`/checkout/details?plan=${key}`} className="w-full">Choose for ${plan.price}<Check size={16}/></Button></div></Card>}
