import {Link} from '@tanstack/react-router'; import {ArrowUpRight,Eye,EyeOff} from 'lucide-react'; import {useState,type ButtonHTMLAttributes,type InputHTMLAttributes,type ReactNode} from 'react'; import {twMerge} from 'tailwind-merge'; import {money,type Plan} from '@/lib/vexo-data';
export const cn=(...v:(string|false|undefined)[])=>twMerge(v.filter(Boolean).join(' '))
function VexoMark({className}:{className?:string}){return <svg aria-hidden="true" viewBox="0 0 42 42" className={cn('h-9 w-9',className)}><path d="M3 6h9.2L21 27.5 29.8 6H39L25.1 36h-8.2L3 6Z" fill="currentColor"/><path d="M12.2 6h8.6l4.3 10.5-4.2 10.3L12.2 6Z" fill="var(--brand)"/></svg>}
export function Logo({compact=false,className}:{compact?:boolean;className?:string}){return <Link to="/" aria-label="VEXO FUNDED home" className={cn('inline-flex items-center gap-3',className)}><span className="grid h-10 w-10 place-items-center rounded-sm border border-line-strong bg-ink text-action"><VexoMark/></span>{!compact&&<span className="font-display text-base font-bold uppercase leading-none"><span className="text-bright">VEXO</span><span className="ml-1.5 text-brand">FUNDED</span><small className="mt-1 block font-body text-[8px] font-medium uppercase text-dim kicker">Trading capital</small></span>}</Link>}
const variants={primary:'bg-action text-action-foreground font-bold shadow-action hover:bg-action/90',secondary:'border border-line-strong bg-panel text-bright hover:border-brand/55 hover:bg-panel-raised',ghost:'text-copy hover:bg-soft hover:text-bright',outline:'border border-brand/45 bg-brand/5 text-brand-soft hover:bg-brand/12'}
export function Button({to,variant='primary',size='md',className,children,...p}:ButtonHTMLAttributes<HTMLButtonElement>&{to?:string;variant?:keyof typeof variants;size?:'sm'|'md'|'lg';children:ReactNode}){const c=cn('inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-sm uppercase tracking-[.04em] transition active:translate-y-px disabled:opacity-50',variants[variant],size==='sm'?'px-4 py-2 text-xs':size==='lg'?'px-7 py-3.5 text-sm':'px-5 py-2.5 text-xs',className); return to?<Link to={to} className={c}>{children}</Link>:<button className={c}{...p}>{children}</button>}
export function Card({children,className,hover=true}: {children:ReactNode;className?:string;hover?:boolean}){return <div className={cn('relative rounded-md border border-line bg-card shadow-card',hover&&'transition duration-200 hover:-translate-y-0.5 hover:border-brand/35 hover:bg-panel',className)}>{children}</div>}
export function Badge({children,tone='neutral',className}:{children:ReactNode;tone?:'neutral'|'brand'|'success'|'warning'|'error';className?:string}){return <span className={cn('inline-flex items-center gap-1.5 rounded-sm border px-2.5 py-1 text-[10px] font-semibold uppercase kicker',tone==='brand'?'border-brand/35 bg-brand/10 text-brand-soft':tone==='success'?'border-success/30 bg-success/10 text-success':tone==='warning'?'border-warning/30 bg-warning/10 text-warning':tone==='error'?'border-error/30 bg-error/10 text-error':'border-line bg-soft text-muted',className)}>{children}</span>}
export function Section({children,className}:{children:ReactNode;className?:string}){return <section className={cn('relative border-b border-line py-16 md:py-24',className)}><div className="mx-auto max-w-7xl px-5 sm:px-6">{children}</div></section>}
export function Eyebrow({children,className}:{children:ReactNode;className?:string}){return <div className={cn('mb-4 flex items-center gap-2 font-mono text-[10px] font-medium uppercase text-brand kicker before:h-px before:w-6 before:bg-brand',className)}>{children}</div>}
export function Field({label,type='text',...p}:InputHTMLAttributes<HTMLInputElement>&{label:string}){const[show,setShow]=useState(false);return <label className="block"><span className="mb-2 block text-xs font-medium uppercase text-muted kicker">{label}</span><span className="relative block"><input type={type==='password'?(show?'text':'password'):type} className="w-full rounded-sm border border-line bg-background px-4 py-3 text-sm text-bright outline-none transition placeholder:text-dim focus:border-brand focus:ring-1 focus:ring-brand/25" {...p}/>{type==='password'&&<button type="button" aria-label="Show password" onClick={()=>setShow(!show)} className="absolute right-3 top-3 text-dim hover:text-bright">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button>}</span></label>}
export function AccountCard({plan}:{plan:Plan}){return <Card className={cn('group flex h-full flex-col overflow-hidden p-5',plan.popular&&'border-brand/55')}><div className="absolute inset-x-0 top-0 h-0.5 bg-brand opacity-0 transition group-hover:opacity-100"/><div className="flex items-center justify-between"><Badge tone={plan.type==='instant'?'success':'brand'}>{plan.type==='instant'?'Instant':'Challenge'}</Badge>{plan.popular&&<Badge tone="brand">Most selected</Badge>}</div><div className="mt-5 flex items-end justify-between gap-4"><div><p className="text-[10px] uppercase text-dim kicker">Account capital</p><h3 className="num mt-1 text-2xl font-semibold text-bright">{money(plan.size)}</h3></div><div className="text-right"><p className="num text-xl font-semibold text-action">{money(plan.price)}</p><p className="text-[10px] uppercase text-dim">one-time</p></div></div><div className="my-5 border-t border-line"/><dl className="flex-1 space-y-3 text-xs">{plan.profitTarget&&<Spec l="Profit Target" v={money(plan.profitTarget)} tone="success"/>}<Spec l="Daily Loss Limit" v={money(plan.dailyLoss)} tone="error"/>{plan.drawdown&&<Spec l="Max Drawdown" v={money(plan.drawdown)} tone="error"/>}<Spec l="Profit Split" v={`${plan.split}%`} tone="brand"/><Spec l="Funding Type" v={plan.type==='instant'?'Instant':'Two-Step Evaluation'}/></dl><Button to={`/checkout/details?plan=${plan.type}-${plan.size}`} className="mt-5 w-full">Select account <ArrowUpRight size={14}/></Button></Card>}
function Spec({l,v,tone}:{l:string;v:string;tone?:string}){return <div className="flex justify-between gap-3 border-b border-line pb-2 last:border-0"><dt className="text-muted">{l}</dt><dd className={cn('num text-right font-medium',tone==='success'?'text-success':tone==='error'?'text-error':tone==='brand'?'text-brand-soft':'text-bright')}>{v}</dd></div>}
export function Status({status}:{status:string}){const tone=status==='completed'||status==='answered'?'success':status==='rejected'?'error':status.includes('waiting')?'warning':status==='processing'||status==='open'?'brand':'neutral'; return <Badge tone={tone}>{status.replace('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}</Badge>}
