import {Link} from '@tanstack/react-router'; import {Eye,EyeOff} from 'lucide-react'; import {useState,type ButtonHTMLAttributes,type InputHTMLAttributes,type ReactNode} from 'react'; import {twMerge} from 'tailwind-merge'; import {assets,money,type Plan} from '@/lib/vexo-data';
export const cn=(...v:(string|false|undefined)[])=>twMerge(v.filter(Boolean).join(' '))
export function Logo(){return <Link to="/" aria-label="VEXO FUNDED home" className="flex items-center gap-2.5"><span aria-hidden="true" className="grid h-8 w-8 place-items-center rounded-lg border border-brand/30 bg-brand/10 font-mono text-[10px] font-bold text-brand">VEXO</span><span className="font-display text-lg font-semibold"><span className="text-brand">VEXO</span> Funded</span></Link>}
const variants={primary:'bg-action-gradient text-ink font-semibold shadow-action hover:brightness-110',secondary:'border border-line bg-surface text-bright hover:border-brand/50',ghost:'text-bright hover:bg-soft',outline:'border border-brand/40 text-brand-soft hover:bg-brand/10'}
export function Button({to,variant='primary',size='md',className,children,...p}:ButtonHTMLAttributes<HTMLButtonElement>&{to?:string;variant?:keyof typeof variants;size?:'sm'|'md'|'lg';children:ReactNode}){const c=cn('inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-lg transition active:scale-[.98] disabled:opacity-50',variants[variant],size==='sm'?'px-4 py-2 text-sm':size==='lg'?'px-8 py-4':'px-6 py-3 text-sm',className); return to?<Link to={to} className={c}>{children}</Link>:<button className={c}{...p}>{children}</button>}
export function Card({children,className,hover=true}: {children:ReactNode;className?:string;hover?:boolean}){return <div className={cn('relative rounded-xl border border-line bg-card shadow-card',hover&&'transition duration-300 hover:-translate-y-1 hover:border-brand/30',className)}>{children}</div>}
export function Badge({children,tone='neutral',className}:{children:ReactNode;tone?:'neutral'|'brand'|'success'|'warning'|'error';className?:string}){return <span className={cn('inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-medium',tone==='brand'?'border-brand/30 bg-brand/10 text-brand-soft':tone==='success'?'border-success/30 bg-success/10 text-success':tone==='warning'?'border-warning/30 bg-warning/10 text-warning':tone==='error'?'border-error/30 bg-error/10 text-error':'border-line bg-soft text-muted',className)}>{children}</span>}
export function Section({children,className}:{children:ReactNode;className?:string}){return <section className={cn('relative py-20 md:py-28',className)}><div className="mx-auto max-w-7xl px-6">{children}</div></section>}
export function Eyebrow({children,className}:{children:ReactNode;className?:string}){return <div className={cn('mb-3 font-mono text-xs uppercase tracking-[.2em] text-brand',className)}>{children}</div>}
export function Field({label,type='text',...p}:InputHTMLAttributes<HTMLInputElement>&{label:string}){const[show,setShow]=useState(false);return <label className="block"><span className="mb-1.5 block text-sm font-medium text-copy">{label}</span><span className="relative block"><input type={type==='password'?(show?'text':'password'):type} className="w-full rounded-lg border border-line bg-surface px-4 py-3 text-sm text-bright outline-none focus:border-brand/50 focus:ring-1 focus:ring-brand/30" {...p}/>{type==='password'&&<button type="button" aria-label="Show password" onClick={()=>setShow(!show)} className="absolute right-3 top-3 text-dim">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button>}</span></label>}
export function AccountCard({plan}:{plan:Plan}){return <Card className={cn('flex h-full flex-col p-6',plan.popular&&'border-brand/40')}><div className="flex justify-between"><Badge tone={plan.type==='instant'?'success':'brand'}>{plan.type==='instant'?'Instant':'Challenge'}</Badge>{plan.popular&&<Badge tone="brand">Popular</Badge>}</div><h3 className="mt-5 font-display text-3xl font-bold">{money(plan.size)}</h3><p className="mt-1 text-sm text-muted">Trading account</p><div className="my-5 border-t border-line"/><p className="num text-3xl font-bold text-brand-soft">{money(plan.price)}</p><p className="text-xs text-dim">one-time</p><dl className="mt-6 flex-1 space-y-3 text-sm">{plan.profitTarget&&<Spec l="Profit Target" v={money(plan.profitTarget)} tone="success"/>}<Spec l="Daily Loss Limit" v={money(plan.dailyLoss)} tone="error"/>{plan.drawdown&&<Spec l="Max Drawdown" v={money(plan.drawdown)} tone="error"/>}<Spec l="Profit Split" v={`${plan.split}%`} tone="brand"/><Spec l="Funding Type" v={plan.type==='instant'?'Instant':'Two-Step Evaluation'}/></dl><Button to={`/checkout/details?plan=${plan.type}-${plan.size}`} className="mt-6 w-full">Get Funded →</Button></Card>}
function Spec({l,v,tone}:{l:string;v:string;tone?:string}){return <div className="flex justify-between gap-3"><dt className="text-muted">{l}</dt><dd className={cn('num text-right font-medium',tone==='success'?'text-success':tone==='error'?'text-error':tone==='brand'?'text-brand-soft':'text-bright')}>{v}</dd></div>}
export function Status({status}:{status:string}){const tone=status==='completed'||status==='answered'?'success':status==='rejected'?'error':status.includes('waiting')?'warning':status==='processing'||status==='open'?'brand':'neutral'; return <Badge tone={tone}>{status.replace('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}</Badge>}
